#basic dev container with uproot on top
FROM ldmx/dev:latest
RUN apt-get update &&\
    apt-get install python3-pip -y &&\
    ./home/ldmx.sh . python3 -m pip install --upgrade --no-cache-dir \
        uproot \
        numpy \
        rootpy \
        matplotlib
